//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCardsDbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Tags = new HashSet<Tag>();
            this.Words = new HashSet<Word>();
        }
    
        public int Id { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public int Points { get; set; }
        public System.Guid Tocken { get; set; }
        public string Name { get; set; }
        public string LastName { get; set; }
        public string UILanguage { get; set; }
    
        public virtual ICollection<Tag> Tags { get; set; }
        public virtual ICollection<Word> Words { get; set; }
    }
}
