//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VCardsDbConnection
{
    using System;
    using System.Collections.Generic;
    
    public partial class Word
    {
        public Word()
        {
            this.Tags = new HashSet<Tag>();
        }
    
        public int Id { get; set; }
        public System.Guid Uid { get; set; }
        public string Word1 { get; set; }
        public string Translation { get; set; }
        public int UserId { get; set; }
        public int SucceedsCount { get; set; }
        public int FailsCount { get; set; }
        public bool IsIdiom { get; set; }
        public System.DateTime ModifyDate { get; set; }
    
        public virtual User User { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }



}
